export const ACCOUNT_PENDING = 'ACCOUNT_PENDING';
export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS';
export const ACCOUNT_FAILURE = 'ACCOUNT_FAILURE';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';